# templates/secret.yaml

{{- if and .Values.s3.enabled (not .Values.s3.useIAM) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3.secretName | default (include "loki.fullname" .) }}-s3-credentials
  labels:
    {{- include "loki.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.s3.accessKeyId .Values.s3.secretAccessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc | quote }}
  {{- else }}
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  {{- end }}
{{- end }}
