global:
  image:
    repository: grafana/loki
    tag: 2.8.0
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 10Gi

# Service Account Configuration
serviceAccount:
  create: true
  name: ""
  annotations: {}

# S3 Configuration
s3:
  enabled: true
  endpoint: s3.amazonaws.com
  region: us-east-1
  bucketNames:
    chunks: loki-chunks
    ruler: loki-ruler
    admin: loki-admin
  s3ForcePathStyle: false
  secretName: loki-s3-credentials

# Components configuration
components:
  distributor:
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

  ingester:
    replicas: 3
    persistence:
      size: 50Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

  querier:
    replicas: 2
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

  queryFrontend:
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi

  compactor:
    replicas: 1
    persistence:
      size: 100Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 30s

# Networking
service:
  type: ClusterIP
  ports:
    http: 3100
    grpc: 9095

gateway:
  enabled: true
  replicas: 2  # Fixed from typo 'replicas'
  ingress:
    enabled: false
    hosts:
      - loki.example.com
    annotations:
      kubernetes.io/ingress.class: nginx

# Cache configuration
cache_config:
  enable_fifocache: true
  default_validity: 12h
