apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}-query-frontend
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    component: query-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
    component: query-frontend
