apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.fullname" . }}-querier
  labels:
    {{- include "loki.labels" . | nindent 4 }}
    component: querier
spec:
  replicas: {{ .Values.components.querier.replicas }}
  selector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
      component: querier
  template:
    metadata:
      labels:
        {{- include "loki.selectorLabels" . | nindent 8 }}
        component: querier
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "http"
    spec:
      serviceAccountName: {{ include "loki.serviceAccountName" . }}
      containers:
        - name: querier
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - "-target=querier"
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
          resources:
            {{- toYaml .Values.components.querier.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki
      volumes:
        - name: config
          configMap:
            name: {{ include "loki.fullname" . }}-config
